services:
  node1:
    image: opensearchproject/opensearch:latest
    container_name: ${PROJECT_NAME:-opensearch}-node1
    environment:
      - cluster.name=${PROJECT_NAME:-opensearch}-cluster
      - node.name=${PROJECT_NAME:-opensearch}-node1
      - OPENSEARCH_JAVA_OPTS=-Xms${JVM_HEAP_SIZE:-512m} -Xmx${JVM_HEAP_SIZE:-512m} # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}    # Sets the admin user password
      # - OPENSEARCH_INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME:-admin}
      - plugins.security.disabled=${SECURITY_DISABLED:-true}
      - discovery.seed_hosts=${PROJECT_NAME:-opensearch}-node1,${PROJECT_NAME:-opensearch}-node2
      - cluster.initial_cluster_manager_nodes=${PROJECT_NAME:-opensearch}-node1,${PROJECT_NAME:-opensearch}-node2
      - bootstrap.memory_lock=${MEMORY_LOCK:-true}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data1:/usr/share/opensearch/data
    ports:
      # - "9200:9200"
      - "9600:9600"
    networks:
      - cluster_network

  node2:
    image: opensearchproject/opensearch:latest
    container_name: ${PROJECT_NAME:-opensearch}-node2
    environment:
      - cluster.name=${PROJECT_NAME:-opensearch}-cluster
      - node.name=${PROJECT_NAME:-opensearch}-node2
      - OPENSEARCH_JAVA_OPTS=-Xms${JVM_HEAP_SIZE:-512m} -Xmx${JVM_HEAP_SIZE:-512m} # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}    # Sets the admin user password
      # - OPENSEARCH_INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME:-admin}
      - plugins.security.disabled=${SECURITY_DISABLED:-true}
      - discovery.seed_hosts=${PROJECT_NAME:-opensearch}-node1,${PROJECT_NAME:-opensearch}-node2
      - cluster.initial_cluster_manager_nodes=${PROJECT_NAME:-opensearch}-node1,${PROJECT_NAME:-opensearch}-node2
      - bootstrap.memory_lock=${MEMORY_LOCK:-true}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data2:/usr/share/opensearch/data
    ports:
      # - "9201:9200"
      - "9601:9600"
    networks:
      - cluster_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: ${PROJECT_NAME:-opensearch}-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://${PROJECT_NAME:-opensearch}-node1:9200","http://${PROJECT_NAME:-opensearch}-node2:9200"]' #',"http://opensearch-node3:9200"]'
    depends_on:
      - node1
      - node2
      # - opensearch-node3
    networks:
      - cluster_network

  webapp:
    build: ./webapp
    container_name: go-webapp
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - OPENSEARCH_URL=http://${PROJECT_NAME:-opensearch}-node1:9200,http://${PROJECT_NAME:-opensearch}-node2:9200 #,http://opensearch-node3:9200
    depends_on:
      - node1
      - node2
      # - opensearch-node3
    networks:
      - cluster_network

volumes:
  data1:
    name: ${PROJECT_NAME:-opensearch}-data1
  data2:
    name: ${PROJECT_NAME:-opensearch}-data2
  # opensearch-data3:

networks:
  cluster_network:
    driver: bridge