services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      # - "plugins.security.disabled=true"
      - "network.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node:9200"]'
      OPENSEARCH_SSL_VERIFICATION_MODE: 'none'
    depends_on:
      - opensearch

  webapp:
    build: ./webapp
    container_name: go-webapp
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
    depends_on:
      - opensearch

volumes:
  opensearch-data: